//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SQLMigrate.rc
//
#define IDC_TOAST                       11
#define IDC_MONTH                       12
#define IDD_ABOUTBOX                    13
#define IDM_ABOUTBOX                    0x010
#define IDC_BOODSCHAP                   20
#define IDR_MAINFRAME                   128
#define IDD_BOODSCHAP                   130
#define IDD_TOAST                       131
#define IDI_HELP                        132
#define IDI_DIRECTORY                   133
#define IDI_OK                          134
#define IDI_CANCEL                      135
#define IDI_REMOVE                      136
#define IDI_SAVE                        137
#define IDD_CALENDAR                    138
#define IDI_CALENDAR                    139
#define IDD_STEPPER                     140
#define IDC_PRIOR                       141
#define IDC_NEXT                        142
#define IDI_PRIOR                       143
#define IDI_NEXT                        144
#define IDB_SCROLLBAR1                  150
#define IDB_SCROLLBAR2                  151
#define IDB_SCROLLBAR3                  152
#define IDB_SCROLLBAR4                  153
#define IDB_SCROLLBAR5                  154
#define IDB_SCROLLBAR6                  155
#define IDB_SCROLLBAR7                  156
#define IDB_SCROLLBAR8                  157
#define IDB_SCROLLBAR1_125              158
#define IDB_SCROLLBAR2_125              159
#define IDB_SCROLLBAR3_125              160
#define IDB_SCROLLBAR4_125              161
#define IDB_SCROLLBAR5_125              162
#define IDB_SCROLLBAR6_125              163
#define IDB_SCROLLBAR7_125              164
#define IDB_SCROLLBAR8_125              165
#define IDB_SCROLLBAR1_150              166
#define IDB_SCROLLBAR2_150              167
#define IDB_SCROLLBAR3_150              168
#define IDB_SCROLLBAR4_150              169
#define IDB_SCROLLBAR5_150              170
#define IDB_SCROLLBAR6_150              171
#define IDB_SCROLLBAR7_150              172
#define IDB_SCROLLBAR8_150              173
#define IDB_SCROLLBAR1_200              174
#define IDB_SCROLLBAR2_200              175
#define IDB_SCROLLBAR3_200              176
#define IDB_SCROLLBAR4_200              177
#define IDB_SCROLLBAR5_200              178
#define IDB_SCROLLBAR6_200              179
#define IDB_SCROLLBAR7_200              180
#define IDB_SCROLLBAR8_200              181
#define IDD_EXPORT                      200
#define IDD_MIGRATE_WIZARD              201
#define IDS_ABOUTBOX                    202
#define IDR_SYSMENU                     203
#define IDC_SOURCE                      1000
#define IDC_SOURCE_USER                 1001
#define IDC_SOURCE_PASSWORD             1002
#define IDC_TARGET                      1003
#define IDC_TARGET_USER                 1004
#define IDC_TARGET_PASSWORD             1005
#define IDC_TABLESPACE                  1008
#define IDC_DIRECT_MIGRATION            1009
#define IDC_DROP_FILE                   1010
#define IDC_CREATE_FILE                 1011
#define IDC_ALLTABLES                   1012
#define IDC_TABLE                       1013
#define IDC_WHERE                       1014
#define IDC_COMMITLINES                 1015
#define IDC_TOLOGFILE                   1016
#define IDC_LOGLINES                    1017
#define IDC_EXPORT                      1018
#define IDC_CLOSE                       1019
#define IDC_LOG                         1020
#define IDC_PROGRESS1                   1021
#define IDC_PROGRESS2                   1022
#define IDC_STATUS                      1023
#define IDC_PROC_DOEN                   1024
#define IDC_SOURCE_TYPE                 1024
#define IDC_DO_TABLES                   1025
#define IDC_DO_DATA                     1026
#define IDC_SEQ_DOEN                    1027
#define IDC_TARGET_USER2                1027
#define IDC_TARGET_TYPE                 1027
#define IDC_VERSION                     1028
#define IDC_LOGLINES2                   1028
#define IDC_ESTIMATED                   1028
#define IDC_VERSION2                    1029
#define IDC_COPYRIGHT                   1029
#define IDC_CHECK1                      1029
#define IDC_TRUNCATE                    1029
#define IDC_DO_TRUNCATE                 1029
#define IDC_SOURCE_TYPE2                1030
#define IDC_SOURCE_SCHEMA               1030
#define IDC_SOURCE_SCHEMA2              1031
#define IDC_TARGET_SCHEMA               1031
#define IDC_DO_PRIMARYS                 1032
#define IDC_DO_INDICES                  1033
#define IDC_DO_SEQUENCES                1034
#define IDC_DO_TRIGGERS                 1035
#define IDC_DO_ACCESS                   1036
#define IDC_CHECK2                      1037
#define IDC_DO_FOREIGN                  1037
#define IDC_DO_PRIMARYS2                1038
#define IDC_DO_DELETES                  1038
#define IDC_DO_DATA2                    1039
#define IDC_DO_VIEWS                    1039
#define IDC_BUTT_DIR                    1040
#define IDC_DIRECTORY                   1041
#define IDC_GRP_STATUS                  1042
#define IDC_BUTTON1                     1043
#define IDC_SAVE                        1043
#define ID_THEMA_LIME                   32771
#define ID_THEMA_SKYBLUE                32772
#define ID_THEMA_PURPLE                 32773
#define ID_THEMA_MODERATE               32774
#define ID_THEMA_PUREGRAY               32775
#define ID_THEMA_BLACKWHITE             32776
#define ID_THEMA_MUSTARD                32777
#define ID_THEMA_DARK                   32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        204
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1044
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
