//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by OpenQuery.rc
//
#define IDR_MAINFRAME                   2
#define IDD_CONNECTION                  101
#define IDD_DIALOGBAR                   103
#define IDD_CONNECT                     103
#define IDI_CON_ICON                    104
#define IDI_DISCON_ICON                 105
#define IDR_DATABASE                    106
#define IDI_WORKER                      110
#define IDR_CONNECTBAR                  116
#define IDR_QUERYBAR                    120
#define IDI_ERRORICON                   123
#define IDB_QUERYSTATES                 124
#define IDR_OE_ODBC_POPUP               125
#define IDC_LIST1                       127
#define IDC_BUTTON2                     128
#define IDD_FIND_FILES                  128
#define IDC_BTN_FILEDSN                 128
#define IDC_RESET                       128
#define IDC_CON_TEST                    129
#define IDD_OE_SQLSETTINGS              129
#define IDC_BTN_SAVEDSN                 129
#define IDC_LIST2                       130
#define IDC_BTN_LOGFILE                 130
#define IDC_BUTTON1                     131
#define IDD_NATIVE_SQL                  131
#define IDC_CON_HELP                    131
#define IDC_BTN_TRANSLIB                131
#define IDC_ADD                         131
#define IDC_BIND                        131
#define IDC_BUT_FONT                    131
#define IDC_BUTTON3                     132
#define IDC_BTN_RDBMS                   132
#define IDC_CON_DELETE                  133
#define IDC_EDIT1                       134
#define IDC_OE_SQLPREFETCHLINES         134
#define IDD_VARIABLES                   134
#define IDC_VAR1                        134
#define IDC_CUR_CONNECTION              135
#define IDC_OE_SQLTERMINATOR            135
#define IDC_VAR2                        135
#define IDD_REBIND                      135
#define IDC_EDIT2                       136
#define IDC_EDIT_NATIVE_SQL             136
#define IDC_SIZE1                       136
#define IDC_FONT                        136
#define IDB_BITMAP1                     136
#define IDB_RDBMS_OBJECTS               136
#define IDC_CHECK1                      137
#define IDC_WHOLE_WORD                  137
#define IDC_EXEC1                       137
#define IDC_COMBO1                      138
#define IDC_FIND_FINDWHAT               138
#define IDC_CON_DATASOURCE              138
#define IDC_TYPE1                       138
#define IDC_DATATYPE                    138
#define IDR_MENU1                       138
#define IDR_OE_TABLES_POPUP             138
#define IDC_TYPE2                       140
#define IDC_SIZE2                       141
#define IDC_EXEC2                       142
#define IDB_STATISTICS                  144
#define IDC_VAR3                        144
#define IDB_HISTORY                     145
#define IDC_TYPE3                       145
#define IDD_CONNECTBAR                  146
#define IDC_SIZE3                       146
#define IDC_EXEC3                       147
#define IDC_VAR4                        149
#define IDC_TYPE4                       150
#define IDC_SIZE4                       151
#define IDC_EXEC4                       152
#define IDC_FILE_TYPES                  1003
#define IDC_FILE_DIRECTORY              1004
#define IDC_MATCH_CASE                  1005
#define IDC_REGULAR_EXPRESSIONS         1006
#define IDC_SUBFOLDERS                  1007
#define IDC_SAVEBEFORE                  1008
#define IDC_COLLAPSELIST                1009
#define IDC_BROWSEDIR                   1010
#define IDC_OE_STATICSQL1               1011
#define IDC_OE_STATICSQL2               1012
#define IDC_APPLY                       1012
#define IDC_OPT_USER                    1015
#define IDC_CHECK3                      1016
#define IDC_OPT_PWD                     1016
#define IDC_CON_DRIVER                  1017
#define IDC_CON_FILE_DSN                1018
#define IDC_CON_SAVE_DSN                1019
#define IDC_TRACE_CONN                  1020
#define IDC_CON_TRACEFILE               1021
#define IDC_CON_CATALOG                 1022
#define IDC_CON_TRANSLIB                1023
#define IDC_CON_READONLY                1024
#define IDC_CON_DEAD                    1025
#define IDC_CON_QUIET                   1026
#define IDC_CON_LOGINTIMEOUT            1027
#define IDC_CON_CONNTIMEOUT             1028
#define IDC_CON_METADATAID              1029
#define IDC_CON_PACKETSIZE              1031
#define IDC_CON_CURSORLIB               1032
#define IDC_CON_AUTOIPD                 1033
#define IDC_CON_AUTOCOMMIT              1034
#define IDC_CON_TRANSOPTION             1035
#define IDC_CON_ISOLATION               1036
#define IDC_CON_DETAILS                 1037
#define IDC_CON_HELPEX                  1038
#define IDC_CON_SIMPLE                  1039
#define IDC_INOUT1                      1040
#define IDC_INOUT2                      1041
#define IDC_REBIND                      1041
#define IDC_INOUT3                      1042
#define IDC_INOUT4                      1043
#define ID_BUT_CONNECT                  40001
#define ID_BUT_DISCONNECT               40002
#define ID_ODBC_CONNECT                 40005
#define ID_ODBC_DISCONNECT              40006
#define ID_ODBC_CURRENT_CONNECTION      40007
#define ID_VIEW_CONNECTBAR              40008
#define ID_SCRIPT_EXECUTE               40009
#define ID_SCRIPT_EXECUTECURRENT        40010
#define ID_SCRIPT_CURRENT               40011
#define ID_SCRIPT_EXECUTESTEP           40012
#define ID_SCRIPT_NEXTERROR             40013
#define ID_SCRIPT_PREVERROR             40014
#define ID_ODBC_BEGIN                   40022
#define ID_ODBC_COMMIT                  40023
#define ID_ODBC_ROLLBACK                40024
#define ID_VIEW_DATABASEBAR             40026
#define IDC_CON_LIST                    40029
#define ID_QUERY_STATISTICS             40030
#define IDC_CON_USER                    40030
#define ID_QUERY_OUTPUT                 40031
#define IDC_CON_PASSWORD                40031
#define ID_QUERY_HISTORY                40032
#define IDC_CON_SAFTY                   40032
#define ID_QUERY_ROTATE                 40033
#define ID_QUERY_SIZEHEADER             40034
#define IDC_CON_DATASOURCES             40034
#define ID_QUERY_BEGIN                  40035
#define ID_BUTTON40036                  40036
#define ID_QUERY_PREV                   40037
#define ID_QUERY_NEXT                   40038
#define ID_QUERY_NEXTPAGE               40039
#define ID_QUERY_END                    40040
#define ID_QUERY_EXCEL                  40041
#define ID_QUERY_SETTINGS               40042
#define ID_QUERY_GRID                   40043
#define ID_QUERY_PAGEBACK               40044
#define ID_FPW_REFRESH_ODBC             40045
#define ID_QUERY_SIZEDATA               40046
#define ID_BUTTON40047                  40047
#define ID_QUERY_SIZEBOTH               40047
#define ID_QUERY_PREVPAGE               40048
#define ID_QUERY_HTML                   40049
#define ID_VIEW_FIND_PANEL              40050
#define ID_SCRIPT_FINDTABLE             40051
#define ID_SCRIPT_TABLEDDL              40052
#define ID_SCRIPT_NATIVE                40054
#define ID_SESSION_ODBCREPORT           40055
#define ID_QUERY_TXT                    40056
#define ID_SESSIONSTATUS                40058
#define ID_SCRIPT_VARIABLES             40059
#define ID_SUPPORT                      40060
#define ID_HELP_BUG                     40061
#define ID_HELP_FEATURE                 40062
#define ID_HELP_SFNET                   40063
#define ID_HELP_GITHUB                  40064
#define ID_POPUP_SELECT                 40065
#define ID_CBAR_SEL100                  40066
#define ID_TEST_SELECTFIRST100          40067
#define ID_TABLE_DDL                    40068
#define ID_TABLE_FIRST                  40069

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         40070
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
