//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by QueryTool.rc
//
#define IDCANCEL2                       3
#define IDC_TOAST                       11
#define IDC_MONTH                       12
#define IDM_ABOUTBOX                    0x010
#define IDC_BOODSCHAP                   20
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDD_BOODSCHAP                   130
#define IDD_TOAST                       131
#define IDI_HELP                        132
#define IDI_DIRECTORY                   133
#define IDI_OK                          134
#define IDI_CANCEL                      135
#define IDI_REMOVE                      136
#define IDI_SAVE                        137

#define IDD_CALENDAR                    138
#define IDI_CALENDAR                    139
#define IDD_STEPPER                     140
#define IDC_PRIOR                       141
#define IDC_NEXT                        142
#define IDI_PRIOR                       143
#define IDI_NEXT                        144

#define IDB_SCROLLBAR1                  150
#define IDB_SCROLLBAR2                  151
#define IDB_SCROLLBAR3                  152
#define IDB_SCROLLBAR4                  153
#define IDB_SCROLLBAR5                  154
#define IDB_SCROLLBAR6                  155
#define IDB_SCROLLBAR7                  156
#define IDB_SCROLLBAR8                  157

#define IDB_SCROLLBAR1_125              158
#define IDB_SCROLLBAR2_125              159
#define IDB_SCROLLBAR3_125              160
#define IDB_SCROLLBAR4_125              161
#define IDB_SCROLLBAR5_125              162
#define IDB_SCROLLBAR6_125              163
#define IDB_SCROLLBAR7_125              164
#define IDB_SCROLLBAR8_125              165

#define IDB_SCROLLBAR1_150              166
#define IDB_SCROLLBAR2_150              167
#define IDB_SCROLLBAR3_150              168
#define IDB_SCROLLBAR4_150              169
#define IDB_SCROLLBAR5_150              170
#define IDB_SCROLLBAR6_150              171
#define IDB_SCROLLBAR7_150              172
#define IDB_SCROLLBAR8_150              173

#define IDB_SCROLLBAR1_200              174
#define IDB_SCROLLBAR2_200              175
#define IDB_SCROLLBAR3_200              176
#define IDB_SCROLLBAR4_200              177
#define IDB_SCROLLBAR5_200              178
#define IDB_SCROLLBAR6_200              179
#define IDB_SCROLLBAR7_200              180
#define IDB_SCROLLBAR8_200              181

#define IDD_CONNECTION                  201
#define IDD_DIALOGBAR                   202
#define IDD_CONNECT                     203
#define IDI_CON_ICON                    204
#define IDI_DISCON_ICON                 205
#define IDR_DATABASE                    206
#define IDI_WORKER                      207
#define IDR_CONNECTBAR                  208
#define IDR_QUERYBAR                    209
#define IDI_ERRORICON                   210
#define IDB_QUERYSTATES                 211
#define IDR_OE_ODBC_POPUP               212
#define IDC_BTN_FILEDSN                 214
#define IDC_RESET                       214
#define IDC_CON_TEST                    215
#define IDD_OE_SQLSETTINGS              215
#define IDC_BTN_SAVEDSN                 215
#define IDC_LIST2                       216
#define IDC_BTN_LOGFILE                 216
#define IDC_BUTTON1                     217
#define IDD_NATIVE_SQL                  217
#define IDC_CON_HELP                    217
#define IDC_BTN_TRANSLIB                217
#define IDC_ADD                         217
#define IDC_BIND                        217
#define IDC_BUT_FONT                    217
#define IDC_BUTT_10                     217
#define IDC_BUTTON3                     218
#define IDC_BTN_RDBMS                   218
#define IDC_BUTT_25                     218
#define IDC_CON_DELETE                  219
#define IDC_BUTT_ANY                    219
#define IDC_EDIT1                       220
#define IDC_OE_SQLPREFETCHLINES         220
#define IDD_VARIABLES                   220
#define IDC_VAR1                        220
#define IDC_TEXT                        220
#define IDC_CONN_STRING                 220
#define IDC_CUR_CONNECTION              221
#define IDC_OE_SQLTERMINATOR            221
#define IDC_VAR2                        221
#define IDD_REBIND                      221
#define IDC_EDIT2                       222
#define IDC_EDIT_NATIVE_SQL             222
#define IDC_SIZE1                       222
#define IDC_FONT                        222
#define IDB_BITMAP1                     222
#define IDB_RDBMS_OBJECTS               222
#define IDC_CHECK1                      223
#define IDC_WHOLE_WORD                  223
#define IDC_EXEC1                       223
#define IDC_META                        223
#define IDC_MY_CONNECT                  223
#define IDC_COMBO1                      224
#define IDC_FIND_FINDWHAT               224
#define IDC_CON_DATASOURCE              224
#define IDC_TYPE1                       224
#define IDC_DATATYPE                    224
#define IDR_MENU1                       224
#define IDR_OE_TABLES_POPUP             224
#define IDC_SQL_LEN                     224
#define IDC_TYPE2                       225
#define IDC_CHARSET                     225
#define IDC_TRANSLATION                 225
#define IDC_SIZE2                       226
#define IDC_EXEC2                       227
#define IDC_CHARACTERSET                227
#define IDB_STATISTICS                  228
#define IDC_VAR3                        228
#define IDB_HISTORY                     229
#define IDC_TYPE3                       229
#define IDD_CONNECTBAR                  230
#define IDC_SIZE3                       230
#define IDC_EXEC3                       231
#define IDC_VAR4                        232
#define IDC_TYPE4                       233
#define IDC_SIZE4                       234
#define IDC_EXEC4                       235
#define IDR_POPUP_EDIT                  236
#define ID_STATUSBAR_PANE1              237
#define ID_STATUSBAR_PANE2              238
#define IDS_STATUS_PANE1                239
#define IDS_STATUS_PANE2                240
#define IDS_TOOLBAR_STANDARD            241
#define IDS_TOOLBAR_CUSTOMIZE           242
#define ID_VIEW_CUSTOMIZE               243
#define IDR_SQLScriptTYPE               244
#define ID_WINDOW_MANAGER               245
#define ID_VIEW_FILEVIEW                246
#define ID_VIEW_INFOVIEW                247
#define ID_VIEW_TABLEVIEW               248
#define ID_OPEN                         249
#define ID_OPEN_WITH                    250
#define ID_DUMMY_COMPILE                251
#define ID_CLASS_ADD_MEMBER_FUNCTION    252
#define ID_CLASS_ADD_MEMBER_VARIABLE    253
#define ID_CLASS_DEFINITION             254
#define ID_CLASS_PROPERTIES             255
#define ID_NEW_FOLDER                   256
#define ID_SORT_MENU                    257
#define ID_SORTING_GROUPBYTYPE          258
#define ID_SORTING_SORTALPHABETIC       259
#define ID_SORTING_SORTBYTYPE           260
#define ID_SORTING_SORTBYACCESS         261
#define ID_VIEW_OUTPUTWND               262
#define IDS_OBJECT_VIEW                 263
#define IDS_ODBC_VIEW                   264
#define IDS_OUTPUT_WND                  265
#define IDI_FILE_VIEW                   266
#define IDI_FILE_VIEW_HC                267
#define IDI_CLASS_VIEW                  268
#define IDI_CLASS_VIEW_HC               269
#define IDI_OUTPUT_WND                  270
#define IDI_OUTPUT_WND_HC               271
#define IDR_EXPLORER                    272
#define IDB_EXPLORER_24                 273
#define IDR_SORT                        274
#define IDB_SORT_24                     275
#define IDR_POPUP_SORT                  276
#define IDR_POPUP_EXPLORER              277
#define IDB_FILE_VIEW                   278
#define IDB_FILE_VIEW_24                279
#define IDB_CLASS_VIEW                  280
#define IDB_CLASS_VIEW_24               281
#define IDR_MENU_IMAGES                 282
#define IDB_MENU_IMAGES_24              283
#define ID_TOOLS_MACRO                  284
#define IDR_OUTPUT_POPUP                285
#define IDR_THEME_MENU                  286
#define ID_SET_STYLE                    287
#define ID_VIEW_APPLOOK_WIN_2000        288
#define ID_VIEW_APPLOOK_OFF_XP          289
#define ID_VIEW_APPLOOK_WIN_XP          290
#define ID_VIEW_APPLOOK_OFF_2003        291
#define ID_VIEW_APPLOOK_VS_2005         292
#define ID_VIEW_APPLOOK_VS_2008         293
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   294
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  295
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 296
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   297
#define ID_VIEW_APPLOOK_WINDOWS_7       298
#define IDS_FIND_TAB1                   299
#define IDS_FIND_TAB2                   300
#define IDS_FIND_TAB3                   301
#define IDS_EXPLORER                    302
#define IDS_EDIT_MENU                   303
#define IDD_OE_DOCUMENT                 310
#define IDD_OE_SETTINGS                 314
#define IDS_DIRECTORY_VIEW              315
#define ID_FPW_DRIVES                   316
#define ID_FPW_EXPLORER                 317
#define ID_FPW_FILTER                   318
#define ID_FPW_TABFILTER                319
#define ID_FPW_TABLE                    320
#define ID_PROPERTIES                   321
#define IDR_SYSMENU                     322
#define IDD_DONATE                      323
#define IDB_PAYPAL                      325
#define IDC_CON_STRING                  326
#define IDD_FIND_FILES                  327
#define IDD_CON_STRING                  328
#define IDC_OE_WORKBOOK_TAB             1000
#define IDC_OESA_LIST                   1000
#define IDC_EF_ALL_WINDOWS              1001
#define IDC_OEA_LICENSE                 1001
#define IDC_OEB_COL_BLK_DELETE_SPACE    1001
#define IDC_OEC_CLASS                   1001
#define IDC_OEGT_INFO                   1001
#define IDC_OEP_CREATED                 1001
#define IDC_OETF_KEYWORD                1001
#define IDC_OET_ADD_TEMPL               1001
#define IDC_OE_BACKUP                   1001
#define IDC_PFC_BACKGROUND              1001
#define IDC_PPS_BLACK_AND_WHITE         1001
#define IDC_EF_COUNT                    1002
#define IDC_OEA_LOGO                    1002
#define IDC_OEB_COL_BLK_LEAVE_CUR_AT_BEG 1002
#define IDC_OEC_DELIMITERS              1002
#define IDC_OEGT_WHERE_FROM1            1002
#define IDC_OEP_DRIVE_USAGE             1002
#define IDC_OETF_MIN_LENGTH             1002
#define IDC_OET_CATEGORY                1002
#define IDC_OE_BACKUP_DIR               1002
#define IDC_PFC_CATEGORY                1002
#define IDC_PPS_BOTTOM                  1002
#define IDC_FILE_TYPES                  1003
#define IDC_EF_DOWN                     1003
#define IDC_OEB_COL_BLK_LEAVE_CUR_AT_END 1003
#define IDC_OEC_FILE_EXTENSIONS         1003
#define IDC_OEGT_WHERE_FROM2            1003
#define IDC_OEP_LAST_MODIFIED           1003
#define IDC_OETF_MIN_LENGTH_SPIN        1003
#define IDC_OET_DEL_TEMPL               1003
#define IDC_OE_BACKUP_DIR_CHANGE        1003
#define IDC_PFC_FONT_BOLD               1003
#define IDC_PPS_FOOTER                  1003
#define IDC_FILE_DIRECTORY              1004
#define IDC_EF_FIND_NEXT                1004
#define IDC_OEB_COL_BLK_LEAVE_SPACE     1004
#define IDC_OEC_FILE_TYPE               1004
#define IDC_OEGT_WHERE_FROM3            1004
#define IDC_OEP_LINES                   1004
#define IDC_OETF_NAME                   1004
#define IDC_OET_EDIT_TEMPL              1004
#define IDC_OE_BACKUP_NAME              1004
#define IDC_PFC_FONT_ITALIC             1004
#define IDC_PPS_HEADER                  1004
#define IDC_MATCH_CASE                  1005
#define IDC_EF_MARK_ALL                 1005
#define IDC_OEB_DEL_A_BS_DELETE_BLOCK   1005
#define IDC_OEC_INDENT_SIZE             1005
#define IDC_OEGT_WHERE_TO               1005
#define IDC_OEP_MEMORY_ALLOCATED        1005
#define IDC_OETF_TEXT                   1005
#define IDC_OET_LIST_IF_ALTERNATIVE     1005
#define IDC_OE_BACKUP_TO_DIR            1005
#define IDC_PFC_FONT_NAME               1005
#define IDC_PPS_LEFT                    1005
#define IDC_REGULAR_EXPRESSIONS         1006
#define IDC_EF_MATCH_CASE               1006
#define IDC_OEB_KEEP_BLOCK_MARKING      1006
#define IDC_OEC_INDENT_SIZE_SPIN        1006
#define IDC_OEP_MEMORY_USAGE            1006
#define IDC_OET_MOVE_DOWN_TEMPL         1006
#define IDC_OE_BACKUP_TO_FILE           1006
#define IDC_PFC_FONT_SIZE               1006
#define IDC_PPS_RIGHT                   1006
#define IDC_SUBFOLDERS                  1007
#define IDC_EF_MATCH_WHOLE_WORD         1007
#define IDC_OEB_TAB_INDENT_BLOCK        1007
#define IDC_OEC_INDENT_TYPE_NONE        1007
#define IDC_OEP_PATH                    1007
#define IDC_OET_MOVE_UP_TEMPL           1007
#define IDC_OE_DEF_EXT                  1007
#define IDC_PFC_FONT_UNDERLINE          1007
#define IDC_PPS_TOP                     1007
#define IDC_SAVEBEFORE                  1008
#define IDC_EF_REGEXP                   1008
#define IDC_OEB_TYPING_OVERWRITE_BLOCK  1008
#define IDC_OEC_INDENT_TYPE_DEFAULT     1008
#define IDC_OEP_UNDO_MEMORY             1008
#define IDC_OET_TEMPL_LIST              1008
#define IDC_OE_FILE_AUTOSCROLL_AFTER_RELOAD 1008
#define IDC_PFC_FOREGROUND              1008
#define IDC_COLLAPSELIST                1009
#define IDC_EF_REGEXP_FIND              1009
#define IDC_OEB_KEEP_BLOCK_MARKING_AFTER_DROP 1009
#define IDC_OEC_INDENT_TYPE_SMART       1009
#define IDC_OE_FILE_DETECT_CHANGES      1009
#define IDC_PFC_SAMPLE                  1009
#define IDC_BROWSEDIR                   1010
#define IDC_EF_REGEXP_REPLACE           1010
#define IDC_OEC_INSERT_SPACES           1010
#define IDC_OE_FILE_LOCKING             1010
#define IDC_OE_STATICSQL1               1011
#define IDC_EF_REPLACE                  1011
#define IDC_OEC_KEEP_TABS               1011
#define IDC_OE_FILE_MEMMAP_FOR_BIG      1011
#define IDC_OE_STATICSQL2               1012
#define IDC_APPLY                       1012
#define IDC_EF_REPLACE_ALL              1012
#define IDC_OEC_LANGUAGE                1012
#define IDC_OE_FILE_MEMMAP_THRESHOLD    1012
#define IDC_EF_REPLACE_IN_SELECTION     1013
#define IDC_OEC_LINE_NUMBERS            1013
#define IDC_OE_FILE_OVERWRITE_READONLY  1013
#define IDC_EF_REPLACE_IN_WHOLE_FILE    1014
#define IDC_OEC_NORMALIZE_KEYWORDS      1014
#define IDC_OE_FILE_RELOAD_CHANGED      1014
#define IDC_OPT_USER                    1015
#define IDC_EF_REPLACE_TEXT             1015
#define IDC_OEC_TAB_SIZE                1015
#define IDC_OE_FILE_SAVE_ON_SWITH       1015
#define IDC_CHECK3                      1016
#define IDC_OPT_PWD                     1016
#define IDC_EF_SEARCH_TEXT              1016
#define IDC_OEC_TAB_SIZE_SPIN           1016
#define IDC_OE_GEN_KEYMAP_LAYOUT        1016
#define IDC_CON_DRIVER                  1017
#define IDC_EF_UP                       1017
#define IDC_OEC_VISIBLE_SPACES          1017
#define IDC_OE_GEN_LOCALE               1017
#define IDC_CON_FILE_DSN                1018
#define IDC_EF_TRANSFORM_BACKSLASH_EXPR 1018
#define IDC_OE_GEN_MAXIMIZE_FIRST_DOC   1018
#define IDC_CON_SAVE_DSN                1019
#define IDC_OE_GEN_MULTIPLE_INST        1019
#define IDC_TRACE_CONN                  1020
#define IDC_OE_GEN_NEW_DOC_ON_STARTUP   1020
#define IDC_CON_TRACEFILE               1021
#define IDC_OE_GEN_SAVE_CURS_N_BOOKMARKS 1021
#define IDC_CON_CATALOG                 1022
#define IDC_OE_GEN_SAVE_MAIN_WIN_POS    1022
#define IDC_CON_TRANSLIB                1023
#define IDC_OE_GEN_WORK_DIR_FOLLOWS_DOC 1023
#define IDC_CON_READONLY                1024
#define IDC_OE_MAX_UNDO_COUNT           1024
#define IDC_CON_DEAD                    1025
#define IDC_OE_MAX_UNDO_COUNT_SPIN      1025
#define IDC_CON_QUIET                   1026
#define IDC_OE_MAX_UNDO_MEM             1026
#define IDC_CON_LOGINTIMEOUT            1027
#define IDC_OE_MAX_UNDO_MEM_SPIN        1027
#define IDC_CON_CONNTIMEOUT             1028
#define IDC_OE_TRUNCATE_SPACES          1028
#define IDC_CON_METADATAID              1029
#define IDC_OE_UNDO_AFTER_SAVING        1029
#define IDC_OE_CURSOR_BEYOND_EOL        1030
#define IDC_CON_PACKETSIZE              1031
#define IDC_OE_CURSOR_BEYOND_EOF        1031
#define IDC_CON_CURSORLIB               1032
#define IDC_CON_AUTOIPD                 1033
#define IDC_CON_AUTOCOMMIT              1034
#define IDC_CON_TRANSOPTION             1035
#define IDC_CON_ISOLATION               1036
#define IDC_CON_DETAILS                 1037
#define IDC_CON_HELPEX                  1038
#define IDC_CON_SIMPLE                  1039
#define IDC_INOUT1                      1040
#define IDC_INOUT2                      1041
#define IDC_REBIND                      1041
#define IDC_INOUT3                      1042
#define IDC_INOUT4                      1043
#define IDC_CUSTOM1                     1044
#define IDC_STATIC1                     1045
#define IDC_STATIC2                     1046
#define IDC_STATIC3                     1047
#define IDC_STATIC4                     1048
#define IDC_EDIT3                       1049
#define IDC_TAB                         1050
#define IDC_PAYPAL                      1051
#define IDI_OE_BIG_SMILE                1101
#define IDB_OE_EXPLORER_STATE_LIST      1201
#define IDR_OPENEDITOR                  1301
#define IDR_OE_CBAR_POPUP               1302
#define IDR_OE_DRIVERS_POPUP            1303
#define IDR_OE_EDIT_POPUP               1304
#define IDR_OE_EXPLORER_POPUP           1305
#define IDR_OE_REGEXP_FIND_POPUP        1306
#define IDR_OE_REGEXP_REPLACE_POPUP     1307
#define IDR_OE_WORKBOOK_POPUP           1308
#define IDD_OE_ABOUTBOX                 1401
#define IDD_OE_EDIT_FIND                1402
#define IDD_OE_EDIT_REPLACE             1403
#define IDD_OE_BACKUP                   1404
#define IDD_OE_BLOCKS                   1405
#define IDD_OE_CLASSES                  1406
#define IDD_OE_EDITING                  1407
#define IDD_OE_FILES                    1408
#define IDD_OE_FILE_INFO                1409
#define IDD_OE_FILE_SETTINGS            1410
#define IDD_OE_GENERAL                  1411
#define IDD_OE_GOTO                     1412
#define IDD_OE_TEMPLATES                1413
#define IDD_OE_TEMPLATE_FORM            1414
#define IDD_OE_PRINT_PAGE_SETUP         1415
#define IDD_OE_PROP_FONT_COLORS         1416
#define IDD_OE_WORKBOOK_BAR             1417
#define IDD_OE_SAVE_ALL                 1418
#define ID_BUT_CONNECT                  40001
#define ID_BUT_DISCONNECT               40002
#define ID_ODBC_DATABASE                40003
#define ID_ODBC_CONNECT                 40005
#define ID_ODBC_DISCONNECT              40006
#define ID_ODBC_CURRENT_CONNECTION      40007
#define ID_VIEW_CONNECTBAR              40008
#define ID_SCRIPT_EXECUTE               40009
#define ID_SCRIPT_EXECUTECURRENT        40010
#define ID_SCRIPT_CURRENT               40011
#define ID_SCRIPT_EXECUTESTEP           40012
#define ID_SCRIPT_NEXTERROR             40013
#define ID_SCRIPT_PREVERROR             40014
#define ID_ODBC_BEGIN                   40022
#define ID_ODBC_COMMIT                  40023
#define ID_ODBC_ROLLBACK                40024
#define ID_VIEW_DATABASEBAR             40026
#define IDC_CON_LIST                    40029
#define ID_QUERY_STATISTICS             40030
#define IDC_CON_USER                    40030
#define ID_QUERY_OUTPUT                 40031
#define IDC_CON_PASSWORD                40031
#define ID_QUERY_HISTORY                40032
#define IDC_CON_SAFTY                   40032
#define ID_QUERY_ROTATE                 40033
#define ID_QUERY_SIZEHEADER             40034
#define IDC_CON_DATASOURCES             40034
#define ID_QUERY_BEGIN                  40035
#define ID_BUTTON40036                  40036
#define ID_QUERY_PREV                   40037
#define ID_QUERY_NEXT                   40038
#define ID_QUERY_NEXTPAGE               40039
#define ID_QUERY_END                    40040
#define ID_QUERY_EXCEL                  40041
#define ID_QUERY_SETTINGS               40042
#define ID_QUERY_GRID                   40043
#define ID_QUERY_PAGEBACK               40044
#define ID_FPW_REFRESH_ODBC             40045
#define ID_QUERY_SIZEDATA               40046
#define ID_BUTTON40047                  40047
#define ID_QUERY_SIZEBOTH               40047
#define ID_QUERY_PREVPAGE               40048
#define ID_QUERY_HTML                   40049
#define ID_VIEW_FIND_PANEL              40050
#define ID_SCRIPT_FINDTABLE             40051
#define ID_SCRIPT_TABLEDDL              40052
#define ID_SCRIPT_NATIVE                40054
#define ID_SESSION_ODBCREPORT           40055
#define ID_QUERY_TXT                    40056
#define ID_SESSIONSTATUS                40058
#define ID_SCRIPT_VARIABLES             40059
#define ID_SUPPORT                      40060
#define ID_HELP_BUG                     40061
#define ID_HELP_FEATURE                 40062
#define ID_HELP_SFNET                   40063
#define ID_HELP_GITHUB                  40064
#define ID_POPUP_SELECT                 40065
#define ID_CBAR_SEL100                  40066
#define ID_TEST_SELECTFIRST100          40067
#define ID_TABLE_DDL                    40068
#define ID_TABLE_FIRST                  40069
#define ID_TEST                         50000
#define ID_CBAR_DOCKING                 50001
#define ID_CBAR_HIDE                    50002
#define ID_EDIT_BKM_GET_0               50003
#define ID_EDIT_BKM_GET_1               50004
#define ID_EDIT_BKM_GET_2               50005
#define ID_EDIT_BKM_GET_3               50006
#define ID_EDIT_BKM_GET_4               50007
#define ID_EDIT_BKM_GET_5               50008
#define ID_EDIT_BKM_GET_6               50009
#define ID_EDIT_BKM_GET_7               50010
#define ID_EDIT_BKM_GET_8               50011
#define ID_EDIT_BKM_GET_9               50012
#define ID_EDIT_BKM_NEXT                50013
#define ID_EDIT_BKM_PREV                50014
#define ID_EDIT_BKM_REMOVE_ALL          50015
#define ID_EDIT_BKM_SET_0               50016
#define ID_EDIT_BKM_SET_1               50017
#define ID_EDIT_BKM_SET_2               50018
#define ID_EDIT_BKM_SET_3               50019
#define ID_EDIT_BKM_SET_4               50020
#define ID_EDIT_BKM_SET_5               50021
#define ID_EDIT_BKM_SET_6               50022
#define ID_EDIT_BKM_SET_7               50023
#define ID_EDIT_BKM_SET_8               50024
#define ID_EDIT_BKM_SET_9               50025
#define ID_EDIT_BKM_TOGGLE              50026
#define ID_EDIT_CAPITALIZE              50027
#define ID_EDIT_COLUMN_SEL              50028
#define ID_EDIT_COMMENT                 50029
#define ID_EDIT_COPY_BOOKMARKED         50030
#define ID_EDIT_COPY_N_APPEND           50031
#define ID_EDIT_CUT_BOOKMARKED          50032
#define ID_EDIT_CUT_N_APPEND            50033
#define ID_EDIT_DATETIME_STAMP          50034
#define ID_EDIT_DELETE                  50035
#define ID_EDIT_DELETE_BOOKMARKED       50036
#define ID_EDIT_DELETE_LINE             50037
#define ID_EDIT_DELETE_WORD_TO_LEFT     50038
#define ID_EDIT_DELETE_WORD_TO_RIGHT    50039
#define ID_EDIT_EXPAND_TEMPLATE         50040
#define ID_EDIT_FILE_SETTINGS           50041
#define ID_EDIT_FIND_MATCH              50042
#define ID_EDIT_FIND_MATCH_N_SELECT     50043
#define ID_EDIT_FIND_NEXT               50044
#define ID_EDIT_FIND_PREVIOUS           50045
#define ID_EDIT_GOTO                    50046
#define ID_EDIT_GO_LINE                 50047
#define ID_EDIT_INDENT                  50048
#define ID_EDIT_INVERT_CASE             50049
#define ID_EDIT_LOWER                   50050
#define ID_EDIT_NEXT                    50051
#define ID_EDIT_NORMALIZE_TEXT          50052
#define ID_EDIT_PERMANENT_SETTINGS      50053
#define ID_EDIT_PREVIOUS                50054
#define ID_EDIT_PRINT_PAGE_SETUP        50055
#define ID_EDIT_SCROLL_CENTER           50056
#define ID_EDIT_SCROLL_DOWN             50057
#define ID_EDIT_SCROLL_UP               50058
#define ID_EDIT_SELECT_LINE             50059
#define ID_EDIT_SELECT_WORD             50060
#define ID_EDIT_SORT                    50061
#define ID_EDIT_STREAM_SEL              50062
#define ID_EDIT_TABIFY                  50063
#define ID_EDIT_TABIFY_LEADING          50064
#define ID_EDIT_TOGGLES_SEL             50065
#define ID_EDIT_UNCOMMENT               50066
#define ID_EDIT_UNDENT                  50067
#define ID_EDIT_UNTABIFY                50068
#define ID_EDIT_UPPER                   50069
#define ID_EDIT_VIEW_LINE_NUMBERS       50070
#define ID_EDIT_VIEW_WHITE_SPACE        50071
#define ID_FILE_CLOSE_ALL               50072
#define ID_FILE_FIND_IN_FILE            50073
#define ID_FILE_RELOAD                  50074
#define ID_FILE_SAVE_ALL                50075
#define ID_FILE_SYNC_LOCATION           50076
#define ID_FPW_GOTO_DEF_DIR             50077
#define ID_FPW_OPEN                     50078
#define ID_FPW_REFRESH                  50079
#define ID_FPW_REFRESH_DRIVERS          50080
#define ID_FPW_SET_DEF_DIR              50081
#define ID_INDICATOR_BLOCK_TYPE         50082
#define ID_INDICATOR_FILE_LINES         50083
#define ID_INDICATOR_FILE_TYPE          50084
#define ID_INDICATOR_LINE               50085
#define ID_INDICATOR_MODIFIED           50086
#define ID_INDICATOR_POS                50087
#define ID_INDICATOR_SCROLL_POS         50088
#define ID_INDICATOR_CUR_CHAR           50089
#define ID_REGEXP_FIND_TAB              50090
#define ID_REGEXP_FIND_ANY_CHAR         50091
#define ID_REGEXP_FIND_ZERO_OR_MORE     50092
#define ID_REGEXP_FIND_ONE_OR_MORE      50093
#define ID_REGEXP_FIND_BOL              50094
#define ID_REGEXP_FIND_EOL              50095
#define ID_REGEXP_FIND_SET              50096
#define ID_REGEXP_FIND_NOT_SET          50097
#define ID_REGEXP_FIND_OR               50098
#define ID_REGEXP_FIND_ESC              50099
#define ID_REGEXP_FIND_ALNUM            50100
#define ID_REGEXP_FIND_ALPHA            50101
#define ID_REGEXP_FIND_DIGIT            50102
#define ID_REGEXP_FIND_XDIGIT           50103
#define ID_REGEXP_FIND_IDENTIFIER       50104
#define ID_REGEXP_FIND_RATIONAL         50105
#define ID_REGEXP_FIND_QUOTED           50106
#define ID_REGEXP_REPLACE_WHAT_FIND     50107
#define ID_REGEXP_REPLACE_TAGEXP_1      50108
#define ID_REGEXP_REPLACE_TAGEXP_2      50109
#define ID_REGEXP_REPLACE_TAGEXP_3      50110
#define ID_REGEXP_REPLACE_TAGEXP_4      50111
#define ID_REGEXP_REPLACE_TAGEXP_5      50112
#define ID_REGEXP_REPLACE_TAGEXP_6      50113
#define ID_REGEXP_REPLACE_TAGEXP_7      50114
#define ID_REGEXP_REPLACE_TAGEXP_8      50115
#define ID_REGEXP_REPLACE_TAGEXP_9      50116
#define ID_VIEW_FILE_PANEL              50117
#define ID_VIEW_WORKBOOK                50118
#define ID_WINDOW_LAST                  50119
#define ID_APP_ON_THE_WEB               50120
#define ID_THEMA_LIME                   50121
#define ID_THEMA_SKYBLUE                50122
#define ID_THEMA_PURPLE                 50123
#define ID_THEMA_MUSTARD                50124
#define ID_THEMA_MODERATE               50125
#define ID_THEMA_PUREGRAY               50126
#define ID_THEMA_BLACKWHITE             50127
#define ID_THEMA_DARK                   50128
#define ID_DONATION                     50129
#define ID_TOOLS_SQLMIGRATION           50130
#define ID_TOOLS_QUERYREWRITER          50131
#define ID_TOOLS_REWRITER               50132
#define ID_APP_DBLKEYACCEL_FIRST        0xDF00
#define ID_APP_DBLKEYACCEL_LAST         0xDFFF

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        330
#define _APS_NEXT_COMMAND_VALUE         50133
#define _APS_NEXT_CONTROL_VALUE         1053
#define _APS_NEXT_SYMED_VALUE           100
#endif
#endif
